const fs = require('fs');
const path = require('path');
const pool = require('../config/db');
const mysql = require('mysql2');

async function backupDatabase() {
  const backupDir = path.resolve(__dirname, '..', 'backups');
  if (!fs.existsSync(backupDir)) {
    fs.mkdirSync(backupDir, { recursive: true });
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = path.join(backupDir, `db-backup-${timestamp}.sql`);
  const stream = fs.createWriteStream(backupPath, { encoding: 'utf8' });

  stream.write('-- Database backup generated by backend/scripts/backup-db.js\n');
  stream.write(`-- Generated: ${new Date().toISOString()}\n`);
  stream.write('SET FOREIGN_KEY_CHECKS = 0;\n\n');

  try {
    const [tables] = await pool.query('SHOW TABLES');
    const tableKey = Object.keys(tables[0] || {})[0];
    if (!tableKey) {
      throw new Error('No tables found in database.');
    }

    for (const row of tables) {
      const tableName = row[tableKey];
      stream.write(`-- Table structure for ${tableName}\n`);
      stream.write(`DROP TABLE IF EXISTS \`${tableName}\`;\n`);

      const [createRows] = await pool.query(`SHOW CREATE TABLE \`${tableName}\``);
      const createSql = createRows[0]['Create Table'] || createRows[0]['Create View'] || Object.values(createRows[0])[1];
      stream.write(`${createSql};\n\n`);

      const [rowsData] = await pool.query(`SELECT * FROM \`${tableName}\``);
      if (rowsData.length === 0) {
        continue;
      }

      stream.write(`-- Dumping data for ${tableName} (${rowsData.length} rows)\n`);
      const columns = Object.keys(rowsData[0]).map(col => `\`${col}\``).join(', ');
      const chunkSize = 200;

      for (let i = 0; i < rowsData.length; i += chunkSize) {
        const chunk = rowsData.slice(i, i + chunkSize);
        const values = chunk.map(row => {
          const rowValues = Object.values(row).map(value => {
            if (value === null || value === undefined) return 'NULL';
            if (typeof value === 'number') return value.toString();
            if (typeof value === 'boolean') return value ? '1' : '0';
            return mysql.escape(value.toString());
          });
          return `(${rowValues.join(', ')})`;
        }).join(',\n');

        stream.write(`INSERT INTO \`${tableName}\` (${columns}) VALUES\n${values};\n`);
      }
      stream.write('\n');
    }

    stream.write('SET FOREIGN_KEY_CHECKS = 1;\n');
    console.log(`Backup completed: ${backupPath}`);
  } catch (error) {
    console.error('Backup failed:', error);
  } finally {
    stream.end();
    if (pool && typeof pool.end === 'function') {
      await pool.end();
    }
  }
}

backupDatabase().catch(err => {
  console.error(err);
  process.exit(1);
});
