
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'rw' | 'sw' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // ─────────────────────────────────────────────── ENGLISH ──
  en: {
    // Navigation
    home: 'Home', about: 'About Us', contact: 'Contact', login: 'Login', sign_out: 'Sign Out',
    contracts: 'Contracts', users: 'Users', system_report: 'System Report',
    create_contract: 'Create Contract',
    contract_confirmation_title: 'Contract Confirmation',
    contract_confirmation_subtitle: 'Confirmation of Agreement',
    contract_to: 'To',
    contract_date: 'Date',
    contract_confirmation_statement: 'This is to confirm that Eco-Smart Poultry Care System (the "Seller") and',
    contract_buyer_label: 'the Buyer',
    contract_confirmation_identifier: 'have agreed to the terms of the contract identified by number',
    contract_system: 'System',
    contract_quantity: 'Quantity',
    contract_total_price: 'Total price',
    contract_deposit_received: 'Deposit received',
    contract_remaining_balance: 'Remaining balance',
    contract_delivery_address: 'Delivery/Installation address',
    seller_signature: 'Seller Signature',
    buyer_signature: 'Buyer Signature',
    live_monitor: 'Live Monitor', ai_predictions: 'AI Predictions', financials: 'Financials',
    user_mgmt: 'User Management', device_mgmt: 'Device Management', settings: 'Settings',
    language: 'Language', administration: 'Administration', poultry_portal: 'Poultry Portal',
    app_title: 'ECO-SMART POULTRY CARE',
    app_tagline: 'Efficient Environmental Monitoring & Farm Management',
    // Hero
    hero_title: 'Eco-Smart Poultry Care',
    hero_subtitle: 'An IoT-integrated platform designed for precision hatchery monitoring and control.',
    access_portal: 'Access Admin Portal', capstone_badge: 'Academic Capstone Project 2024–2025',
    // Home sections
    innovative_core: 'Innovative Core', engineering_future: 'Engineering the Future of Hatcheries',
    solar_autonomy: 'Solar Autonomy',
    solar_autonomy_desc: 'Hybrid energy systems ensuring continuous life support for embryos without grid dependency.',
    cognitive_edge: 'Cognitive Edge',
    cognitive_edge_desc: 'On-site neural logic processing for instantaneous environment correction and safety protocols.',
    cloud_intelligence: 'Cloud Intelligence',
    cloud_intelligence_desc: 'A global telemetry network providing deep insights into batch viability and farm metrics.',
    target_viability: 'Target Viability', energy_savings: 'Energy Savings',
    telemetry: 'Telemetry', real_time: 'Real-time', core_uptime: 'Core Uptime',
    designed_professional: 'Designed for Professional Excellence',
    pioneering_integration: 'Pioneering the integration of IoT and Renewable Energy to meet sustainable development goals in agricultural research.',
    eco_smart_system: '© 2025 ECO-SMART SYSTEM', research_project: 'CAPSTONE RESEARCH PROJECT',
    faculty_engineering: 'FACULTY OF ENGINEERING',
    // Farmer Dashboard
    live_dashboard: 'Live Dashboard', last_updated: 'Last updated',
    environmental_conditions: 'Environmental Conditions', temperature: 'Temperature', humidity: 'Humidity',
    light_intensity: 'Light Intensity', air_quality: 'Air Quality',
    energy_source_type: 'Energy Source Type', total_energy_used: 'Total Energy Used',
    kwh_consumed: 'kWh Consumed', electrical_params: 'Electrical Parameters',
    voltage: 'Voltage', current: 'Current', solar: 'Solar', main_grid: 'Main Grid',
    active: 'Active', inactive: 'Inactive', normal: 'Normal', good: 'Good',
    warning: 'Warning', critical: 'Critical', optimal: 'Optimal', status: 'Status',
    power: 'Power Strategy', dim: 'Dim', bright: 'Bright',
    aqi_good: 'AQI Good', aqi_moderate: 'AQI Moderate', aqi_poor: 'AQI Poor',
    parameters_chart: 'All Parameters – Live Chart',
    feed_water_recommendation: 'Feed & Water Recommendation',
    chick_type: 'Chick Type',
    age_months: 'Age (months)',
    get_recommendation: 'Get Recommendation',
    processing: 'Processing...',
    stage: 'Stage',
    recommended_feed: 'Recommended Feed',
    daily_feed_intake: 'Daily Feed Intake',
    recommended_water: 'Recommended Water',
    nutrient_targets: 'Nutrient Targets',
    notes: 'Notes',
    feed_notes: 'Feed Notes',
    broiler: 'Broiler',
    layer: 'Layer',
    dual_purpose: 'Dual-purpose',
    local_indigenous: 'Local/Indigenous',
    specific_type: 'Specific Type',
    specific_type_placeholder: 'e.g. indigenous, improved, meat-type, egg-type',
    indigenous: 'Indigenous',
    improved_breed: 'Improved Breed',
    meat_type: 'Meat-type',
    egg_type: 'Egg-type',
    total_chickens: 'Total Chickens',
    flock_totals: 'Flock Totals (per day)',
    feed_total_per_day: 'Total Feed',
    water_total_per_day: 'Total Water',
    feed_water_desc: 'Select chick type, specific type, age, and flock size to get feed/water recommendations and nutrient targets.',
    record_feeding_activity: 'Record Feeding Activity',
    feed_type: 'Feed Type',
    feed_type_placeholder: 'e.g. Broiler Starter, Layer Ration',
    quantity_supplied_kg: 'Quantity Supplied (kg)',
    feeding_time: 'Feeding Time',
    save_record: 'Save Record',
    feeding_history: 'Feeding History',
    no_feeding_records: 'No feeding records yet.',
    saved: 'Saved.',
    deleted: 'Deleted.',
    farm_size: 'Farm Size',
    farm_location: 'Farm Location',
    temp: 'Temperature', hum: 'Humidity',
    // Staff Dashboard
    financial_dashboard: 'Financial Dashboard', add_transaction: 'Add Transaction',
    edit_transaction: 'Edit Transaction', transaction_history: 'Transaction History',
    type: 'Type', category: 'Category', amount: 'Amount', date: 'Date', description: 'Description',
    income: 'Income', expense: 'Expense', feed: 'Feed', medication: 'Medication',
    equipment: 'Equipment', utilities: 'Utilities', labor: 'Labor', sales: 'Sales', other: 'Other',
    other_description: 'Describe the "Other" category...',
    add_record: 'Add Record', save_changes: 'Save Changes',
    cancel: 'Cancel', edit: 'Edit', delete: 'Delete',
    total_income: 'Total Income', total_expense: 'Total Expenses', net_balance: 'Net Balance',
    no_records: 'No records yet.',
    // User Management
    user_management: 'User Management', full_name: 'Full Name', email: 'Email',
    role: 'Role', actions: 'Actions', add_user: 'Add User', search_users: 'Search users...',
    admin: 'Admin', staff: 'Staff', farmer: 'Farmer', operator: 'Operator',
    // Account Settings
    account_settings: 'Account Settings', profile_info: 'Profile Information',
    change_password: 'Change Password', save: 'Save', update: 'Update', phone: 'Phone', address: 'Address',
    // Incubator/Device
    device_management: 'Device Management', incubator: 'Incubator', total_eggs: 'Total Eggs',
    expected_hatch: 'Expected Hatch', days_remaining: 'Days Remaining', health: 'Health', add_device: 'Add Device',
    // Predictions
    prediction_title: 'AI Predictions', model_accuracy: 'Model Accuracy',
    run_prediction: 'Run Prediction', prediction_results: 'Prediction Results',
    hatch_probability: 'Hatch Probability', risk_level: 'Risk Level', recommendation: 'Recommendation',
    low: 'Low', medium: 'Medium', high: 'High',
    // Contact
    contact_title: 'Get In Touch',
    contact_subtitle: 'Have questions about our egg incubation systems? Our support team is ready to help.',
    send_message: 'Send Us a Message', first_name: 'First Name', last_name: 'Last Name',
    email_address: 'Email Address', subject: 'Subject', your_message: 'Your Message',
    send_btn: 'Send Message', message_sent: 'Message Sent!',
    message_sent_desc: 'Thank you. We will get back to you shortly.',
    send_another: 'Send another message', contact_details: 'Contact Details',
    headquarters: 'Headquarters', connect_with_us: 'Connect With Us', mon_fri: 'Mon–Fri, 8am–5pm (GMT+2)',
    select_subject: 'Select a subject',
    // Login
    login_title: 'Welcome Back', login_subtitle: 'Sign in to access your dashboard',
    password: 'Password', sign_in: 'Sign In', no_account: "Don't have an account?",
    register: 'Register', forgot_password: 'Forgot password?',
    // About
    about_title: 'About This System', about_subtitle: 'A next-generation smart poultry management platform',
    // Common
    loading: 'Loading...', error: 'Error', success: 'Success',
    confirm_delete: 'Are you sure you want to delete this?',
    yes: 'Yes', no: 'No', search: 'Search', export: 'Export',
    refresh: 'Refresh', close: 'Close', submit: 'Submit', back: 'Back', next: 'Next',
    // Additional home/navigation keys
    marketplace: 'Marketplace',
    announcements: 'Announcements',
    at_a_glance: 'At a glance',
    system_summary: 'System summary',
    real_time_monitoring: 'Real-time monitoring: temperature, humidity, and environment status.',
    smart_alerts: 'Smart alerts to reduce losses and improve flock comfort.',
    incubator_tools: 'Incubator & farm management tools for daily operations.',
    analytics_ai: 'Analytics & AI insights to support better decisions.',
    initializing: 'Initializing Systems...',
    // Sidebar / products / announcements
    uploading_product: 'Uploading Product',
    my_products: 'My Products',
    my_announcement: 'My Announcement',
    our_services: 'Our Services',
    my_announcements: 'My Announcements',
    seller_requests: 'Seller Requests',
    customer_dashboard: 'Customer Dashboard',
    seller_dashboard: 'Seller Dashboard',
    edit_delete_announcements: 'Edit / Delete Announcements',
    new_announcement: 'New Announcement',
    create_new_announcement: 'Create New Announcement',
    edit_delete_created_announcements: 'Edit/Delete Created Announcements',
    all_products: 'All Products',
    viewing_products_for_selected_farmer: 'Viewing products for selected farmer.',
    no_products_registered_yet: 'No products registered yet.',
    confirm_delete_product: 'Delete this product?',
  },

  // ─────────────────────────────────────────────── KINYARWANDA ──
  rw: {
    // Navigation
    home: 'Ahabanza', about: 'Abo Turi Bo', contact: 'Twandikire', login: 'Injira', sign_out: 'Sohoka',
    contracts: 'Amasezerano', users: 'Abakoresha', system_report: 'Raporo ya Sisitemu',
    create_contract: 'Hindura Amasezerano',
    contract_confirmation_title: 'Kwemeza Amasezerano',
    contract_confirmation_subtitle: 'Kwemeza Amasezerano',
    contract_to: 'Kuri',
    contract_date: 'Italiki',
    contract_confirmation_statement: 'Ibi ni ukwemeza ko Eco-Smart Poultry Care System ("Uwagurisha") na',
    contract_buyer_label: '"Uwagura"',
    contract_confirmation_identifier: 'bemeye amategeko y amasezerano afite nomero',
    contract_system: 'Sisitemu',
    contract_quantity: 'Umubare',
    contract_total_price: 'Igiciro cyose',
    contract_deposit_received: 'Aubanza yakiriwe',
    contract_remaining_balance: 'Asigaye',
    contract_delivery_address: 'Aderesi yo Gutanga/Kwiyubaka',
    seller_signature: 'Signature y Uwagurisha',
    buyer_signature: 'Signature y Uwagura',
    live_monitor: 'Igenzura ry\'ako kanya', ai_predictions: 'Ubuhanga bw\'AI', financials: 'Imicungire y\'imari',
    user_mgmt: 'Gucunga abakoresha', device_mgmt: 'Gucunga ibikoresho', settings: 'Igenamiterere',
    language: 'Ururimi', administration: 'Ubuyobozi', poultry_portal: 'Isaha y\'Inkoko',
    app_title: 'ECO-SMART POULTRY CARE',
    app_tagline: 'Igenzura Ryiza ry\'Ibidukikije n\'Imicungire y\'Ubworozi',
    // Hero
    hero_title: 'Eco-Smart Poultry Care',
    hero_subtitle: 'Urubuga rwa IoT rwagenewe kugenzura no kugabanya ubushyuhe bw\'amasaka n\'inkoko mu buryo bunoze.',
    access_portal: 'Injira muri Sisitemu', capstone_badge: 'Umushinga w\'Akanama 2024–2025',
    // Home sections
    innovative_core: 'Inovasiya Shingiro', engineering_future: 'Kubaka Ejo h\'Ejo ku Masaka',
    solar_autonomy: 'Gukoreshwa kwa Izuba',
    solar_autonomy_desc: 'Sisitemu y\'imbaraga igizwe hamwe kugira ngo ikiraniro cy\'amagi kikomeze nta gufata amashanyarazi yo hanze.',
    cognitive_edge: 'Ubushishozi bw\'Ubwonko',
    cognitive_edge_desc: 'Gucunga ibidukikije mu gihe kivutse kugira ngo haboneke imyitwarire ikwiriye ya sisitemu.',
    cloud_intelligence: 'Ubwenge bwa Muruhu',
    cloud_intelligence_desc: 'Umuyoboro wa telemetri w\'isi wose utanga amakuru ku birusho by\'imbuto n\'ubukungu bw\'ulurimi.',
    target_viability: 'Intego y\'Ubuzima', energy_savings: 'Ikigereranyo cy\'Imbaraga',
    telemetry: 'Telemetri', real_time: 'Igihe cya Nyawo', core_uptime: 'Igihe Sisitemu Ikora',
    designed_professional: 'Yagenewe Ubuhanga Bwisumbuye',
    pioneering_integration: 'Ubuyobozi bwo guhuza IoT n\'Ingufu Zitwara Imbaraga mu gushyikira intego z\'iterambere rirambye mu bushakashatsi bw\'ubuhinzi.',
    eco_smart_system: '© 2025 ECO-SMART', research_project: 'UMUSHINGA W\'UBUSHAKASHATSI',
    faculty_engineering: 'ISHAMI RY\'INJINIYI',
    // Farmer Dashboard
    live_dashboard: 'Imbaho za kuri iri joro', last_updated: 'Ivugurura rya nyuma',
    environmental_conditions: 'Imiterere y\'Ibidukikije', temperature: 'Ubushyuhe', humidity: 'Umunyevu w\'Ikirere',
    light_intensity: 'Ubushanyuka bw\'Urumuri', air_quality: 'Ubwiza bw\'Umwuka',
    energy_source_type: 'Ubwoko bw\'Ingufu', total_energy_used: 'Ingufu Zose Zakoreshejwe',
    kwh_consumed: 'kWh Zasohotse', electrical_params: 'Ibigereranyo bya Amashanyarazi',
    voltage: 'Voritaji', current: 'Amashanyarazi', solar: 'Izuba', main_grid: 'Amashanyarazi yo Hanze',
    active: 'Ikora', inactive: 'Idakora', normal: 'Bisanzwe', good: 'Byiza',
    warning: 'Iburira', critical: 'Ingorane', optimal: 'Bikiri Neza', status: 'Imiterere',
    power: 'Ingamba z\'Ingufu', dim: 'Inzuzi', bright: 'Urumuri Rwinshi',
    aqi_good: 'Umwuka Mwiza', aqi_moderate: 'Umwuka wa Hagati', aqi_poor: 'Umwuka Mubi',
    parameters_chart: 'Imibare Yose – Ishusho y\'Ibihe',
    feed_water_recommendation: 'Inama ku Ifunguro n\'Amazi',
    chick_type: 'Ubwoko bw\'Inkoko',
    age_months: 'Imyaka (amezi)',
    get_recommendation: 'Shaka Inama',
    processing: 'Birimo gukorwa...',
    stage: 'Icyiciro',
    recommended_feed: 'Ifunguro Risabwa',
    daily_feed_intake: 'Ifunguro ku munsi',
    recommended_water: 'Amazi Asabwa',
    nutrient_targets: 'Intego z\'Imirire',
    notes: 'Ibisobanuro',
    feed_notes: 'Inama ku Ifunguro',
    broiler: 'Broiler',
    layer: 'Layer',
    dual_purpose: 'Ikoreshwa Byombi',
    local_indigenous: 'Inkoko Gakondo',
    specific_type: 'Ubwoko Bwahiswemo',
    specific_type_placeholder: 'urugero: gakondo, iyatejwe, iy\'inyama, iy\'amagi',
    indigenous: 'Gakondo',
    improved_breed: 'Ibyatejwe',
    meat_type: 'Iby\'inyama',
    egg_type: 'Iby\'amagi',
    total_chickens: 'Umubare w\'Inkoko',
    flock_totals: 'Igiteranyo cy\'Umunsi',
    feed_total_per_day: 'Ifunguro Ryose',
    water_total_per_day: 'Amazi Yose',
    feed_water_desc: 'Hitamo ubwoko, ubwoko bwihariye, imyaka (amezi), n\'umubare w\'inkoko kugira ngo ubone inama ku ifunguro/amazi n\'imirire.',
    record_feeding_activity: 'Andika Igihe cyo Kugaburira',
    feed_type: 'Ubwoko bw\'Ifunguro',
    feed_type_placeholder: 'urugero: Starter, Grower, Layer',
    quantity_supplied_kg: 'Ingano Itanzwe (kg)',
    feeding_time: 'Igihe cyo Kugaburira',
    save_record: 'Bika',
    feeding_history: 'Amateka yo Kugaburira',
    no_feeding_records: 'Nta mateka arahari.',
    saved: 'Byabitswe.',
    deleted: 'Byasibwe.',
    farm_size: 'Ingano y\'umurima',
    farm_location: 'Aho umurima uherereye',
    temp: 'Ubushyuhe', hum: 'Umunyevu',
    // Staff Dashboard
    financial_dashboard: 'Imbaho z\'Imari', add_transaction: 'Ongeraho Igikorwa',
    edit_transaction: 'Hindura Igikorwa', transaction_history: 'Amateka y\'Ibikorwa',
    type: 'Ubwoko', category: 'Icyiciro', amount: 'Amafaranga', date: 'Italiki', description: 'Ibisobanuro',
    income: 'Injiza', expense: 'Ibyasohotse', feed: 'Ifunguro', medication: 'Imiti',
    equipment: 'Ibikoresho', utilities: 'Serivisi', labor: 'Akazi', sales: 'Igurisha', other: 'Ibindi',
    other_description: 'Sobanura "ibindi"...',
    add_record: 'Ongeraho Inyandiko', save_changes: 'Bika Impinduka',
    cancel: 'Hagarika', edit: 'Hindura', delete: 'Siba',
    total_income: 'Injiza Yose', total_expense: 'Ibyasohotse Byose', net_balance: 'Inyungu Isigaye',
    no_records: 'Nta makuru arahari.',
    // User Management
    user_management: 'Gucunga Abakoresha', full_name: 'Amazina Yuzuye', email: 'Imeyili',
    role: 'Uruhare', actions: 'Ibikorwa', add_user: 'Ongeraho Umukoreshwa', search_users: 'Shakisha abakoresha...',
    admin: 'Umuyobozi', staff: 'Umukozi', farmer: 'Umuhinzi', operator: 'Uwakoresha',
    // Account Settings
    account_settings: 'Igenamiterere ry\'Konti', profile_info: 'Amakuru y\'Umwirondoro',
    change_password: 'Hindura Ijambobanga', save: 'Bika', update: 'Vugurura', phone: 'Telefoni', address: 'Aderesi',
    // Incubator/Device
    device_management: 'Gucunga Ibikoresho', incubator: 'Ikiraniro', total_eggs: 'Amagi Yose',
    expected_hatch: 'Itariki Itezwe', days_remaining: 'Iminsi Isigaye', health: 'Ubuzima', add_device: 'Ongeraho Igikoresho',
    // Predictions
    prediction_title: 'Ubuhanga bw\'AI', model_accuracy: 'Inganwe y\'Ingingo',
    run_prediction: 'Tangira Ubuhanga', prediction_results: 'Ibisubizo by\'Ubuhanga',
    hatch_probability: 'Amahirwe yo Gusama', risk_level: 'Urwego rw\'Ingorane', recommendation: 'Inama',
    low: 'Hasi', medium: 'Hagati', high: 'Hejuru',
    // Contact
    contact_title: 'Twandikire', contact_subtitle: 'Ufite ibibazo ku bijyanye n\'ibikoresho byacu? Itsinda ryacu rirateguriye gufasha.',
    send_message: 'Twoherereze Ubutumwa', first_name: 'Izina', last_name: 'Ishema',
    email_address: 'Imeyili', subject: 'Insanganyamatsiko', your_message: 'Ubutumwa Bwawe',
    send_btn: 'Ohereza Ubutumwa', message_sent: 'Ubutumwa Bwoherejwe!',
    message_sent_desc: 'Murakoze. Tuzasubizanya vuba.',
    send_another: 'Ohereza ubutumwa ubundi', contact_details: 'Amakuru y\'Itumanaho',
    headquarters: 'Icyicaro Gikuru', connect_with_us: 'Dutumanaho', mon_fri: 'Ku wa 1–5, 8am–5pm (GMT+2)',
    select_subject: 'Hitamo insanganyamatsiko',
    // Login
    login_title: 'Murakaza Neza', login_subtitle: 'Injira kugira ngo ubonere imbaho zawe',
    password: 'Ijambobanga', sign_in: 'Injira', no_account: 'Nta konti ufite?',
    register: 'Iyandikishe', forgot_password: 'Wibagiwe ijambobanga?',
    // About
    about_title: 'Ibyerekeye Sisitemu', about_subtitle: 'Urubuga rwihangiye rw\'inzobere rw\'ubucuzi bw\'inkoko',
    // Common
    loading: 'Gutegereza...', error: 'Ikosa', success: 'Byagenze Neza',
    confirm_delete: 'Urashaka gusiba ibi?',
    yes: 'Yego', no: 'Oya', search: 'Shakisha', export: 'Bimenyeshe',
    refresh: 'Kongeramwo', close: 'Funga', submit: 'Ohereza', back: 'Garuka', next: 'Komeza',
    // Additional home/navigation keys
    marketplace: 'Isoko',
    announcements: 'Amatangazo',
    at_a_glance: 'Mu ncamake',
    system_summary: 'Ibisobanuro bya Sisitemu',
    real_time_monitoring: 'Igenzura ry\'ako kanya: ubushyuhe, umwuka, n\'ibindi.',
    smart_alerts: 'Ibyitonderwa by\'ubwenge bigamije kugabanya ibihombo no kuzamura imikorere y\'umutungo.',
    incubator_tools: 'Ibikoresho byo gucunga ikiraniro n\'ubuhinzi ku bikorwa bya buri munsi.',
    analytics_ai: 'Isesengura & AI bifasha gufata ibyemezo byiza.',
    initializing: 'Gutangirisha Sisitemu...',
    // Sidebar / products / announcements
    uploading_product: 'Kohereza Igicuruzwa',
    my_products: 'Ibikoresho Byanjye',
    my_announcement: 'Itangazo Ryanjye',
    our_services: 'Serivisi Zacu',
    my_announcements: 'Amatangazo Yanjye',
    seller_requests: 'Ibyasabwe n\'umucuruzi',
    customer_dashboard: 'Imbonerahamwe y\'Umukiriya',
    seller_dashboard: 'Imbonerahamwe y\'Umucuruzi',
    edit_delete_announcements: 'Hindura / Siba Amatangazo',
    new_announcement: 'Itangazo Rishya',
    create_new_announcement: 'Hindura Itangazo Rishya',
    edit_delete_created_announcements: 'Hindura/Siba Amatangazo Wakoze',
    all_products: 'Ibicuruzwa Byose',
    viewing_products_for_selected_farmer: 'Kureba ibicuruzwa by\'umuhinzi wahiswemo.',
    no_products_registered_yet: 'Nta bicuruzwa byanditswe kugeza ubu.',
    confirm_delete_product: 'Urashaka gusiba iki gicuruzwa?',
  },

  // ─────────────────────────────────────────────── KISWAHILI ──
  sw: {
    // Navigation
    home: 'Nyumbani', about: 'Kuhusu Sisi', contact: 'Wasiliana', login: 'Ingia', sign_out: 'Toka',
    contracts: 'Mikataba', users: 'Watumiaji', system_report: 'Ripoti ya Mfumo',
    create_contract: 'Tengeneza Mkataba',
    contract_confirmation_title: 'Uthibitisho wa Mkataba',
    contract_confirmation_subtitle: 'Uthibitisho wa Makubaliano',
    contract_to: 'Kwa',
    contract_date: 'Tarehe',
    contract_confirmation_statement: 'Hii ni kuthibitisha kwamba Eco-Smart Poultry Care System ("Muuzaji") na',
    contract_buyer_label: '"Mnunuzi"',
    contract_confirmation_identifier: 'wamekubaliana juu ya masharti ya mkataba wenye nambari',
    contract_system: 'Mfumo',
    contract_quantity: 'Kiasi',
    contract_total_price: 'Jumla ya bei',
    contract_deposit_received: 'Amana iliyopokelewa',
    contract_remaining_balance: 'Salio lililobaki',
    contract_delivery_address: 'Anwani ya Uwasilishaji/Usakinishaji',
    seller_signature: 'Sahihi ya Muuzaji',
    buyer_signature: 'Sahihi ya Mnunuzi',
    live_monitor: 'Ufuatiliaji wa Moja kwa Moja', ai_predictions: 'Utabiri wa AI', financials: 'Fedha',
    user_mgmt: 'Usimamizi wa Watumiaji', device_mgmt: 'Usimamizi wa Vifaa', settings: 'Mipangilio',
    language: 'Lugha', administration: 'Utawala', poultry_portal: 'Lango la Kuku',
    app_title: 'ECO-SMART POULTRY CARE',
    app_tagline: 'Ufuatiliaji Bora wa Mazingira na Usimamizi wa Shamba',
    // Hero
    hero_title: 'Eco-Smart Poultry Care',
    hero_subtitle: 'Jukwaa la IoT lililoundwa kwa ajili ya ufuatiliaji wa usahihi wa vifaranga na udhibiti.',
    access_portal: 'Ingia Kwenye Paneli', capstone_badge: 'Mradi wa Juu wa Kitaaluma 2024–2025',
    // Home sections
    innovative_core: 'Msingi wa Ubunifu', engineering_future: 'Kuunda Mustakabali wa Vifarangaizi',
    solar_autonomy: 'Uhuru wa Jua',
    solar_autonomy_desc: 'Mifumo ya nishati mseto kuhakikisha msaada wa maisha unaoendelea kwa viini bila kutegemea gridi.',
    cognitive_edge: 'Akili ya Kimawazo',
    cognitive_edge_desc: 'Usindikaji wa mantiki wa neva ndani ya mtambo kwa ajili ya marekebisho ya wakati halisi ya mazingira.',
    cloud_intelligence: 'Akili ya Wingu',
    cloud_intelligence_desc: 'Mtandao wa telemetri ya kimataifa unaotoa maarifa ya kina kuhusu uwezo wa bchi na takwimu za shamba.',
    target_viability: 'Lengo la Uhai', energy_savings: 'Akiba ya Nishati',
    telemetry: 'Telemetri', real_time: 'Wakati Halisi', core_uptime: 'Muda wa Uendeshaji',
    designed_professional: 'Imeundwa kwa Ubora wa Kitaalamu',
    pioneering_integration: 'Kuanzisha ujumuishaji wa IoT na Nishati Mbadala kukidhi malengo ya maendeleo endelevu katika utafiti wa kilimo.',
    eco_smart_system: '© 2025 ECO-SMART', research_project: 'MRADI WA UTAFITI',
    faculty_engineering: 'KITIVO CHA UHANDISI',
    // Farmer Dashboard
    live_dashboard: 'Dashibodi ya Moja kwa Moja', last_updated: 'Ilisasishwa mara ya mwisho',
    environmental_conditions: 'Hali ya Mazingira', temperature: 'Joto', humidity: 'Unyevunyevu',
    light_intensity: 'Ukali wa Mwanga', air_quality: 'Ubora wa Hewa',
    energy_source_type: 'Aina ya Chanzo cha Nishati', total_energy_used: 'Jumla ya Nishati Iliyotumiwa',
    kwh_consumed: 'kWh Zilizotumika', electrical_params: 'Vigezo vya Umeme',
    voltage: 'Voltage', current: 'Mkondo', solar: 'Jua', main_grid: 'Gridi Kuu',
    active: 'Inafanya Kazi', inactive: 'Haifanyi Kazi', normal: 'Kawaida', good: 'Nzuri',
    warning: 'Onyo', critical: 'Hatari', optimal: 'Bora', status: 'Hali',
    power: 'Mkakati wa Nguvu', dim: 'Hafifu', bright: 'Mwanga Mkali',
    aqi_good: 'Hewa Nzuri', aqi_moderate: 'Hewa ya Kati', aqi_poor: 'Hewa Mbaya',
    parameters_chart: 'Vigezo Vyote – Chati ya Wakati Halisi',
    feed_water_recommendation: 'Mapendekezo ya Chakula na Maji',
    chick_type: 'Aina ya Kuku',
    age_months: 'Umri (miezi)',
    get_recommendation: 'Pata Mapendekezo',
    processing: 'Inachakata...',
    stage: 'Hatua',
    recommended_feed: 'Chakula Kinachopendekezwa',
    daily_feed_intake: 'Kiasi cha chakula kwa siku',
    recommended_water: 'Maji Yanayopendekezwa',
    nutrient_targets: 'Viwango vya Virutubisho',
    notes: 'Vidokezo',
    feed_notes: 'Vidokezo vya Chakula',
    broiler: 'Broiler',
    layer: 'Layer',
    dual_purpose: 'Matumizi Mawili',
    local_indigenous: 'Asili/Kienyeji',
    specific_type: 'Aina Mahususi',
    specific_type_placeholder: 'mfano: kienyeji, bora, ya nyama, ya mayai',
    indigenous: 'Kienyeji',
    improved_breed: 'Bora (Improved)',
    meat_type: 'Ya nyama',
    egg_type: 'Ya mayai',
    total_chickens: 'Jumla ya Kuku',
    flock_totals: 'Jumla (kwa siku)',
    feed_total_per_day: 'Jumla ya Chakula',
    water_total_per_day: 'Jumla ya Maji',
    feed_water_desc: 'Chagua aina ya kuku, aina mahsusi, umri (miezi), na idadi ya kuku kupata mapendekezo ya chakula/maji na virutubisho.',
    record_feeding_activity: 'Rekodi Ulishaji',
    feed_type: 'Aina ya Chakula',
    feed_type_placeholder: 'mfano: Starter, Grower, Layer',
    quantity_supplied_kg: 'Kiasi Kilichotolewa (kg)',
    feeding_time: 'Muda wa Kulishe',
    save_record: 'Hifadhi Rekodi',
    feeding_history: 'Historia ya Ulishaji',
    no_feeding_records: 'Hakuna rekodi bado.',
    saved: 'Imehifadhiwa.',
    deleted: 'Imefutwa.',
    farm_size: 'Ukubwa wa shamba',
    farm_location: 'Mahali shamba lilipo',
    temp: 'Joto', hum: 'Unyevu',
    // Staff Dashboard
    financial_dashboard: 'Dashibodi ya Fedha', add_transaction: 'Ongeza Muamala',
    edit_transaction: 'Hariri Muamala', transaction_history: 'Historia ya Miamala',
    type: 'Aina', category: 'Kategoria', amount: 'Kiasi', date: 'Tarehe', description: 'Maelezo',
    income: 'Mapato', expense: 'Matumizi', feed: 'Chakula', medication: 'Dawa',
    equipment: 'Vifaa', utilities: 'Huduma', labor: 'Kazi', sales: 'Mauzo', other: 'Nyingine',
    other_description: 'Eleza kategoria "Nyingine"...',
    add_record: 'Ongeza Rekodi', save_changes: 'Hifadhi Mabadiliko',
    cancel: 'Ghairi', edit: 'Hariri', delete: 'Futa',
    total_income: 'Jumla ya Mapato', total_expense: 'Jumla ya Matumizi', net_balance: 'Bakaa Halisi',
    no_records: 'Hakuna rekodi bado.',
    // User Management
    user_management: 'Usimamizi wa Watumiaji', full_name: 'Jina Kamili', email: 'Barua Pepe',
    role: 'Jukumu', actions: 'Vitendo', add_user: 'Ongeza Mtumiaji', search_users: 'Tafuta watumiaji...',
    admin: 'Msimamizi', staff: 'Wafanyakazi', farmer: 'Mkulima', operator: 'Mwendeshaji',
    // Account Settings
    account_settings: 'Mipangilio ya Akaunti', profile_info: 'Taarifa za Wasifu',
    change_password: 'Badilisha Nywila', save: 'Hifadhi', update: 'Sasisha', phone: 'Simu', address: 'Anwani',
    // Incubator/Device
    device_management: 'Usimamizi wa Vifaa', incubator: 'Kifarangaizi', total_eggs: 'Jumla ya Mayai',
    expected_hatch: 'Hatch Inayotarajiwa', days_remaining: 'Siku Zilizobaki', health: 'Afya', add_device: 'Ongeza Kifaa',
    // Predictions
    prediction_title: 'Utabiri wa AI', model_accuracy: 'Usahihi wa Mfano',
    run_prediction: 'Fanya Utabiri', prediction_results: 'Matokeo ya Utabiri',
    hatch_probability: 'Uwezekano wa Kutotolewa', risk_level: 'Kiwango cha Hatari', recommendation: 'Mapendekezo',
    low: 'Chini', medium: 'Katikati', high: 'Juu',
    // Contact
    contact_title: 'Wasiliana Nasi', contact_subtitle: 'Una maswali kuhusu mifumo yetu ya kuanguliwa mayai? Timu yetu iko tayari kusaidia.',
    send_message: 'Tutumie Ujumbe', first_name: 'Jina la Kwanza', last_name: 'Jina la Familia',
    email_address: 'Barua Pepe', subject: 'Mada', your_message: 'Ujumbe Wako',
    send_btn: 'Tuma Ujumbe', message_sent: 'Ujumbe Umetumwa!',
    message_sent_desc: 'Asante. Tutawasiliana nawe hivi karibuni.',
    send_another: 'Tuma ujumbe mwingine', contact_details: 'Maelezo ya Mawasiliano',
    headquarters: 'Makao Makuu', connect_with_us: 'Unganika Nasi', mon_fri: 'Jumatatu–Ijumaa, 8am–5pm (GMT+2)',
    select_subject: 'Chagua mada',
    // Login
    login_title: 'Karibu Tena', login_subtitle: 'Ingia ili kupata dashibodi yako',
    password: 'Nywila', sign_in: 'Ingia', no_account: 'Huna akaunti?',
    register: 'Jiandikishe', forgot_password: 'Umesahau nywila?',
    // About
    about_title: 'Kuhusu Mfumo Huu', about_subtitle: 'Jukwaa la kisasa la usimamizi wa kuku wa akili',
    // Common
    loading: 'Inapakia...', error: 'Kosa', success: 'Imefanikiwa',
    confirm_delete: 'Una uhakika unataka kufuta hii?',
    yes: 'Ndiyo', no: 'Hapana', search: 'Tafuta', export: 'Hamisha',
    refresh: 'Onyesha Upya', close: 'Funga', submit: 'Wasilisha', back: 'Rudi', next: 'Endelea',
    // Additional home/navigation keys
    marketplace: 'Sokoni',
    announcements: 'Matangazo',
    at_a_glance: 'Kwa muhtasari',
    system_summary: 'Muhtasari wa Mfumo',
    real_time_monitoring: 'Ufuatiliaji wa wakati halisi: joto, unyevunyevu, na hali ya mazingira.',
    smart_alerts: 'Onyo za busara ili kupunguza hasara na kuboresha ustawi wa kundi.',
    incubator_tools: 'Zana za usimamizi wa kifaranga na shamba kwa shughuli za kila siku.',
    analytics_ai: 'Takwimu & AI kwa kusaidia maamuzi bora.',
    initializing: 'Kuanzisha Mifumo...',
    // Sidebar / products / announcements
    uploading_product: 'Kupakia Bidhaa',
    my_products: 'Bidhaa Zangu',
    my_announcement: 'Tangazo Langu',
    our_services: 'Huduma Zetu',
    my_announcements: 'Mitangazo Yangu',
    seller_requests: 'Maombi ya Muuzaji',
    customer_dashboard: 'Dashboard ya Mteja',
    seller_dashboard: 'Dashboard ya Muuzaji',
    edit_delete_announcements: 'Hariri / Futa Matangazo',
    new_announcement: 'Tangazo Jipya',
    create_new_announcement: 'Tengeneza Tangazo Jipya',
    edit_delete_created_announcements: 'Hariri/Futa Matangazo Uliyotengeneza',
    all_products: 'Bidhaa Zote',
    viewing_products_for_selected_farmer: 'Kuangalia bidhaa za muuzaji aliyechaguliwa.',
    no_products_registered_yet: 'Bado hakuna bidhaa zilizosajiliwa.',
    confirm_delete_product: 'Unataka kufuta bidhaa hii?',
  },

  // ─────────────────────────────────────────────── FRANÇAIS ──
  fr: {
    // Navigation
    home: 'Accueil', about: 'À Propos', contact: 'Contact', login: 'Connexion', sign_out: 'Se Déconnecter',
    contracts: 'Contrats', users: 'Utilisateurs', system_report: 'Rapport Système',
    create_contract: 'Créer un contrat',
    contract_confirmation_title: 'Confirmation du contrat',
    contract_confirmation_subtitle: 'Confirmation de l’accord',
    contract_to: 'À',
    contract_date: 'Date',
    contract_confirmation_statement: 'Ceci confirme que Eco-Smart Poultry Care System (le "Vendeur") et',
    contract_buyer_label: 'l"Acheteur"',
    contract_confirmation_identifier: 'ont accepté les termes du contrat identifié par le numéro',
    contract_system: 'Système',
    contract_quantity: 'Quantité',
    contract_total_price: 'Prix total',
    contract_deposit_received: 'Acompte reçu',
    contract_remaining_balance: 'Solde restant',
    contract_delivery_address: 'Adresse de livraison/installation',
    seller_signature: 'Signature du vendeur',
    buyer_signature: 'Signature de l’acheteur',
    live_monitor: 'Surveillance en Direct', ai_predictions: 'Prédictions IA', financials: 'Finances',
    user_mgmt: 'Gestion des Utilisateurs', device_mgmt: 'Gestion des Appareils', settings: 'Paramètres',
    language: 'Langue', administration: 'Administration', poultry_portal: 'Portail Avicole',
    app_title: 'ECO-SMART POULTRY CARE',
    app_tagline: 'Surveillance Environnementale Efficace et Gestion Agricole',
    // Hero
    hero_title: 'Eco-Smart Poultry Care',
    hero_subtitle: 'Une plateforme IoT conçue pour la surveillance et le contrôle de précision des couvoirs.',
    access_portal: 'Accéder au Portail', capstone_badge: 'Projet de Fin d\'Études 2024–2025',
    // Home sections
    innovative_core: 'Cœur Innovant', engineering_future: 'Construire l\'Avenir des Couvoirs',
    solar_autonomy: 'Autonomie Solaire',
    solar_autonomy_desc: 'Systèmes d\'énergie hybrides assurant un support de vie continu pour les embryons sans dépendance au réseau.',
    cognitive_edge: 'Intelligence Cognitive',
    cognitive_edge_desc: 'Traitement logique neuronal sur site pour une correction instantanée de l\'environnement et des protocoles de sécurité.',
    cloud_intelligence: 'Intelligence Cloud',
    cloud_intelligence_desc: 'Un réseau de télémétrie mondial offrant des informations approfondies sur la viabilité des lots et les métriques agricoles.',
    target_viability: 'Viabilité Cible', energy_savings: 'Économies d\'Énergie',
    telemetry: 'Télémétrie', real_time: 'Temps Réel', core_uptime: 'Disponibilité Système',
    designed_professional: 'Conçu pour l\'Excellence Professionnelle',
    pioneering_integration: 'Pionnier de l\'intégration de l\'IoT et des énergies renouvelables pour atteindre les objectifs de développement durable dans la recherche agricole.',
    eco_smart_system: '© 2025 ECO-SMART', research_project: 'PROJET DE RECHERCHE',
    faculty_engineering: 'FACULTÉ DES SCIENCES DE L\'INGÉNIEUR',
    // Farmer Dashboard
    live_dashboard: 'Tableau de Bord en Direct', last_updated: 'Dernière mise à jour',
    environmental_conditions: 'Conditions Environnementales', temperature: 'Température', humidity: 'Humidité',
    light_intensity: 'Intensité Lumineuse', air_quality: 'Qualité de l\'Air',
    energy_source_type: 'Type de Source d\'Énergie', total_energy_used: 'Énergie Totale Utilisée',
    kwh_consumed: 'kWh Consommés', electrical_params: 'Paramètres Électriques',
    voltage: 'Tension', current: 'Courant', solar: 'Solaire', main_grid: 'Réseau Principal',
    active: 'Actif', inactive: 'Inactif', normal: 'Normal', good: 'Bon',
    warning: 'Avertissement', critical: 'Critique', optimal: 'Optimal', status: 'État',
    power: 'Stratégie Énergétique', dim: 'Faible', bright: 'Lumineux',
    aqi_good: 'Qualité Bonne', aqi_moderate: 'Qualité Modérée', aqi_poor: 'Qualité Mauvaise',
    parameters_chart: 'Tous les Paramètres – Graphique en Direct',
    feed_water_recommendation: 'Recommandation Nourriture & Eau',
    chick_type: 'Type de poussin',
    age_months: 'Âge (mois)',
    get_recommendation: 'Obtenir la recommandation',
    processing: 'Traitement...',
    stage: 'Stade',
    recommended_feed: 'Aliment recommandé',
    daily_feed_intake: 'Consommation quotidienne',
    recommended_water: 'Eau recommandée',
    nutrient_targets: 'Objectifs nutritionnels',
    notes: 'Notes',
    feed_notes: 'Notes sur l\'aliment',
    broiler: 'Poulet de chair',
    layer: 'Pondeuse',
    dual_purpose: 'Double usage',
    local_indigenous: 'Local/Autochtone',
    specific_type: 'Type spécifique',
    specific_type_placeholder: 'ex: indigène, améliorée, viande, ponte',
    indigenous: 'Indigène',
    improved_breed: 'Améliorée',
    meat_type: 'Viande',
    egg_type: 'Ponte',
    total_chickens: 'Nombre total de poulets',
    flock_totals: 'Totaux (par jour)',
    feed_total_per_day: 'Aliment total',
    water_total_per_day: 'Eau totale',
    feed_water_desc: 'Sélectionnez le type, le type spécifique, l\'âge (mois) et la taille du lot pour obtenir les recommandations.',
    record_feeding_activity: 'Enregistrer l\'alimentation',
    feed_type: 'Type d\'aliment',
    feed_type_placeholder: 'ex: Démarrage, Croissance, Ponte',
    quantity_supplied_kg: 'Quantité fournie (kg)',
    feeding_time: 'Heure d\'alimentation',
    save_record: 'Enregistrer',
    feeding_history: 'Historique d\'alimentation',
    no_feeding_records: 'Aucun enregistrement pour le moment.',
    saved: 'Enregistré.',
    deleted: 'Supprimé.',
    farm_size: 'Taille de la ferme',
    farm_location: 'Localisation de la ferme',
    temp: 'Température', hum: 'Humidité',
    // Staff Dashboard
    financial_dashboard: 'Tableau de Bord Financier', add_transaction: 'Ajouter une Transaction',
    edit_transaction: 'Modifier une Transaction', transaction_history: 'Historique des Transactions',
    type: 'Type', category: 'Catégorie', amount: 'Montant', date: 'Date', description: 'Description',
    income: 'Revenus', expense: 'Dépenses', feed: 'Alimentation', medication: 'Médicaments',
    equipment: 'Équipement', utilities: 'Services', labor: 'Main-d\'œuvre', sales: 'Ventes', other: 'Autre',
    other_description: 'Décrivez la catégorie "Autre"...',
    add_record: 'Ajouter un Enregistrement', save_changes: 'Enregistrer les Modifications',
    cancel: 'Annuler', edit: 'Modifier', delete: 'Supprimer',
    total_income: 'Revenus Totaux', total_expense: 'Dépenses Totales', net_balance: 'Solde Net',
    no_records: 'Aucun enregistrement.',
    // User Management
    user_management: 'Gestion des Utilisateurs', full_name: 'Nom Complet', email: 'Email',
    role: 'Rôle', actions: 'Actions', add_user: 'Ajouter un Utilisateur', search_users: 'Rechercher des utilisateurs...',
    admin: 'Administrateur', staff: 'Personnel', farmer: 'Agriculteur', operator: 'Opérateur',
    // Account Settings
    account_settings: 'Paramètres du Compte', profile_info: 'Informations du Profil',
    change_password: 'Changer le Mot de Passe', save: 'Enregistrer', update: 'Mettre à Jour',
    phone: 'Téléphone', address: 'Adresse',
    // Incubator/Device
    device_management: 'Gestion des Appareils', incubator: 'Couveuse', total_eggs: 'Total des Œufs',
    expected_hatch: 'Éclosion Prévue', days_remaining: 'Jours Restants', health: 'Santé', add_device: 'Ajouter un Appareil',
    // Predictions
    prediction_title: 'Prédictions IA', model_accuracy: 'Précision du Modèle',
    run_prediction: 'Lancer la Prédiction', prediction_results: 'Résultats des Prédictions',
    hatch_probability: 'Probabilité d\'Éclosion', risk_level: 'Niveau de Risque', recommendation: 'Recommandation',
    low: 'Faible', medium: 'Moyen', high: 'Élevé',
    // Contact
    contact_title: 'Contactez-Nous', contact_subtitle: 'Des questions sur nos systèmes d\'incubation ? Notre équipe est prête à vous aider.',
    send_message: 'Envoyez-Nous un Message', first_name: 'Prénom', last_name: 'Nom',
    email_address: 'Adresse Email', subject: 'Sujet', your_message: 'Votre Message',
    send_btn: 'Envoyer le Message', message_sent: 'Message Envoyé !',
    message_sent_desc: 'Merci. Nous vous recontacterons très prochainement.',
    send_another: 'Envoyer un autre message', contact_details: 'Coordonnées',
    headquarters: 'Siège Social', connect_with_us: 'Connectez-Vous avec Nous', mon_fri: 'Lun–Ven, 8h–17h (GMT+2)',
    select_subject: 'Sélectionnez un sujet',
    // Login
    login_title: 'Bon Retour', login_subtitle: 'Connectez-vous pour accéder à votre tableau de bord',
    password: 'Mot de Passe', sign_in: 'Se Connecter', no_account: 'Vous n\'avez pas de compte ?',
    register: 'S\'inscrire', forgot_password: 'Mot de passe oublié ?',
    // About
    about_title: 'À Propos du Système', about_subtitle: 'Une plateforme de gestion avicole de nouvelle génération',
    // Common
    loading: 'Chargement...', error: 'Erreur', success: 'Succès',
    confirm_delete: 'Êtes-vous sûr de vouloir supprimer ceci ?',
    yes: 'Oui', no: 'Non', search: 'Rechercher', export: 'Exporter',
    refresh: 'Actualiser', close: 'Fermer', submit: 'Soumettre', back: 'Retour', next: 'Suivant',
    // Additional home/navigation keys
    marketplace: 'Marché',
    announcements: 'Annonces',
    at_a_glance: 'En un coup d\'œil',
    system_summary: 'Résumé du système',
    real_time_monitoring: 'Surveillance en temps réel : température, humidité et état de l\'environnement.',
    smart_alerts: 'Alertes intelligentes pour réduire les pertes et améliorer le confort du troupeau.',
    incubator_tools: 'Outils de gestion de la couveuse et de la ferme pour les opérations quotidiennes.',
    analytics_ai: 'Analyses & IA pour aider la prise de décisions.',
    initializing: 'Initialisation des Systèmes...',
    // Sidebar / products / announcements
    uploading_product: 'Téléverser un produit',
    my_products: 'Mes Produits',
    our_services: 'Nos Services',
    my_announcement: 'Mon Annonce',
    my_announcements: 'Mes Annonces',
    seller_requests: 'Demandes de Vendeur',
    customer_dashboard: 'Tableau de Bord Client',
    seller_dashboard: 'Tableau de Bord Vendeur',
    edit_delete_announcements: 'Modifier / Supprimer les Annonces',
    new_announcement: 'Nouvelle Annonce',
    create_new_announcement: 'Créer une Nouvelle Annonce',
    edit_delete_created_announcements: 'Modifier/Supprimer les Annonces Créées',
    all_products: 'Tous les Produits',
    viewing_products_for_selected_farmer: 'Affichage des produits pour l\'éleveur sélectionné.',
    no_products_registered_yet: 'Aucun produit enregistré pour le moment.',
    confirm_delete_product: 'Supprimer ce produit ?',
  },
};

const englishFallback: Record<string, string> = {
  contracts: 'Contracts',
  users: 'Users',
  system_report: 'System Report',
  app_title: 'ECO-SMART POULTRY CARE',
  app_tagline: 'Efficient Environmental Monitoring & Farm Management',
  dashboard: 'Dashboard',
  financial_records: 'Financial Records',
  request_form: 'Request Form',
  image_form: 'Image Form',
  user: 'User',
  operator_role: 'Operator',
  join_platform: 'Join Platform',
  enter_portal: 'Enter Portal',
  quick_guide: 'Quick Guide',
  institutional_portal: 'TUNG CHICKS Ltd',
  hero_main_title_a: 'Tumba College of',
  hero_main_title_b: 'Technology.',
  hero_main_description: 'A professional ecosystem built to manage, track, and empower access to specialized infrastructure. We guide you from lab mastery to startup success.',
  loading_wait: 'Please wait...',
  login_with_account: 'Sign in with your account',
  your_email: 'Your Email',
  login_button: 'Sign in to Dashboard',
  contact_admin: 'Contact Admin',
  login_help: 'Having trouble logging in?',
  create_account: 'Create Account',
  sending: 'Sending...',
  failed_send_message: 'Failed to send message. Please try again.',
  technical_support: 'Technical Support',
  partnership: 'Partnership / Collaboration',
  product_inquiry: 'Product Inquiry',
  feedback: 'Feedback',
  enter_dashboard_portal: 'Enter Dashboard Portal',
  documentation: 'Documentation',
  project_overview_architecture: 'Project Overview & System Architecture',
  about_intro: 'Eco-Smart Poultry Care for Efficient Environmental Monitoring and Farm Management is an advanced IoT-based platform designed to automate poultry farm management, optimize environmental conditions, and support sustainable farming practices. The system leverages real-time data, automation, and machine learning to improve chick survival rates and predict diseases caused by harmful gases and poor environmental conditions.',
  the_problem: 'The Problem',
  our_objective: 'Our Objective',
  problem_points: [
    'Newly hatched chicks cannot move to regulate their temperature, risking overheating or chilling.',
    'Traditional heating (stoves, charcoal) causes uneven temperature and releases harmful gases.',
    'Exposure to dangerous gases increases disease risk for chicks and harms the environment.',
    'Lack of automation makes it hard for farmers to monitor and optimize farm conditions.',
    'No proper management system prevents farmers from tracking performance and making informed decisions.'
  ],
  objective_text: 'The objectives are to create an automated system for the management of poultry using IoT technology that provides an appropriate environment for chicks to grow in after they are hatched, reduces human intervention in the process, increases the survival rate of chicks, and encourages sustainable farming practices in poultry. Additionally, the system will introduce machine learning for predicting diseases that can affect chicks, especially those caused by harmful gases and poor environmental conditions.',
  technical_layers: 'Technical Implementation Layers',
  technical_layers_desc: '<ul><li><strong>Perception Layer:</strong> Real-time sensors for temperature, humidity, air quality (e.g., DHT22, MQ-135), and chick weight.</li><li><strong>Processing Layer:</strong> ESP32 microcontroller for edge data processing, local alarms, and automated control of heating/ventilation.</li><li><strong>Application Layer:</strong> Web dashboard (React), backend API (Node.js/Express), and MySQL database for data storage, visualization, and machine learning-based disease prediction.</li></ul>',
  project_contributors: 'PROJECT TEAM MEMBERS',
  ready_telemetry: 'Ready to view live telemetry?',
  telemetry_cta_text: 'Access the admin dashboard to see real-time data from the brooder sensors and financial logs.',
  perception_layer: 'Perception Layer',
  processing_layer: 'Processing Layer',
  application_layer: 'Application Layer',
  electronics_engineer: 'Electronics Engineer',
  systems_engineer: 'Systems Engineer',
  fullstack_developer: 'Full-Stack Developer',
  live_telemetry_dashboard: 'Live Telemetry Dashboard',
  online: 'Online',
  offline: 'Offline',
  attention_needed: 'Attention Needed',
  all_parameters_graph: 'All Parameters Graph',

  // Financial reports
  financial_report: 'Financial Report',
  start_date: 'Start date',
  end_date: 'End date',
  weekly: 'Weekly',
  monthly: 'Monthly',
  generate_report: 'Generate report',
  period: 'Period',
  records: 'Records',
  report_hint: 'Choose a date range and generate a weekly or monthly summary.',
  report_select_dates_error: 'Please select both start and end dates.',
  report_invalid_dates_error: 'Invalid date range.',
  report_start_after_end_error: 'Start date must be before end date.',
  report_no_rows_error: 'Generate the report first (no rows to export).',
  download_csv: 'Download CSV',
  request_submitted_success: 'Request submitted successfully.',
  request_form_subtitle: 'Submit operational requests for the poultry care platform.',
  request_type: 'Request Type',
  title: 'Title',
  details: 'Details',
  submit_request: 'Submit Request',
  short_request_title: 'Short request title',
  explain_request: 'Explain your request clearly',
  maintenance: 'Maintenance',
  sensor_calibration: 'Sensor Calibration',
  supply_request: 'Supply Request',
  home_hero_images: 'Home Hero Images',
  manage_home_slider: 'Manage the images displayed in the home page slider.',
  upload_new_image: 'Upload New Image',
  image_post_added: 'Image post added successfully.',
  upload_image: 'Upload Image',
  title_optional: 'Title (Optional)',
  display_order: 'Display Order',
  upload_desc: 'Description shown on home page',
  uploading: 'Uploading...',
  publish_home: 'Publish to Home',
  active_gallery: 'Active Gallery',
  images_count: 'Images',
  preview: 'Preview',
  no_image_gallery: 'No image in active gallery yet.',
  order: 'Order',
  edit_transaction_title: 'Edit Transaction',
  add_transaction_title: 'Add Transaction',
  messages_room: 'Messages Room (Contact Inbox)',
  unread: 'unread',
  no_messages_yet: 'No messages received yet.',
  mark_as_read: 'Mark as Read',
  history_log: 'History Log',
  log_energy_bill: 'Log Energy Bill',
  amount_rwf: 'Amount (RWF)',
  enter_amount: 'Enter amount',
  saving: 'Saving…',
  date_col: 'Date',
  category_col: 'Category',
  type_col: 'Type',
  amount_col: 'Amount',
  edit_transaction_btn: 'Edit transaction',
  delete_transaction_btn: 'Delete transaction',
  delete_record_confirm: 'Delete this record from project history?',
  ai_nexus_predictions: 'AI Nexus Predictions',
  predict_intro: 'Our neural algorithms analyze your incubation schedule to provide precision hatch metrics and real-time environmental optimization.',
  predict_results: 'Predict Results',
  hatch_success_probability: 'Disease Prediction Confidence',
  ai_predicted_hatch_date: 'Prediction Date',
  technical_ai_recommendations: 'Technical AI Recommendations',
  awaiting_data: 'Awaiting data input to generate nexus intelligence...',
  predictive_performance_analytics: 'Predictive Performance Analytics',
  historical_accuracy: 'Historical Accuracy',
  model_version: 'Model Version',
  processing_latency: 'Processing Latency',
  deep_flash_learning: 'Deep Flash Learning',
  realtime_edge_logic: 'Real-time edge logic',
};

const kinyarwandaFallback: Record<string, string> = {
  contracts: 'Amasezerano',
  users: 'Abakoresha',
  system_report: 'Raporo ya Sisitemu',
  app_title: 'ECO-SMART POULTRY CARE',
  app_tagline: 'Igenzura Ryiza ry\'Ibidukikije n\'Imicungire y\'Ubworozi',
  dashboard: 'Imbonerahamwe',
  financial_records: 'Inyandiko z’Imari',
  request_form: 'Ifishi y’Ubusabe',
  image_form: 'Ifishi y’Amashusho',
  user: 'Umukoresha',
  operator_role: 'Ukoresha',
  join_platform: 'Injira kuri Platform',
  enter_portal: 'Injira muri Sisitemu',
  quick_guide: 'Ubuyobozi bwihuse',
  institutional_portal: 'TUNG CHICKS Ltd',
  hero_main_title_a: 'Ishuri Rikuru rya Tumba rya',
  hero_main_title_b: 'Ikoranabuhanga.',
  hero_main_description: 'Urubuga rw’umwuga rwubatswe kugira ngo rucunge kandi rukurikirane ibikorwa bya laboratwari n’ibikoresho mu buryo bugezweho.',
  loading_wait: 'Tegereza gato...',
  login_with_account: 'Injira ukoresheje konti yawe',
  your_email: 'Imeyili yawe',
  login_button: 'Injira muri Dashboard',
  contact_admin: 'Vugana na Admin',
  login_help: 'Ufite ikibazo cyo kwinjira?',
  create_account: 'Fungura Konti',
  sending: 'Birimo koherezwa...',
  failed_send_message: 'Kohereza ubutumwa byanze. Ongera ugerageze.',
  technical_support: 'Ubufasha bw’Ikoranabuhanga',
  partnership: 'Ubufatanye',
  product_inquiry: 'Kubaza kuri serivisi',
  feedback: 'Ibitekerezo',
  enter_dashboard_portal: 'Injira muri Dashboard',
  documentation: 'Inyandiko',
  project_overview_architecture: 'Incamake y’Umushinga & Imiterere ya Sisitemu',
  about_intro: 'Eco-Smart Poultry Care ni urubuga rw’IoT ruhuza ibikoresho byo ku murima n’igenzura rya sisitemu mu buryo bw’ikoranabuhanga.',
  the_problem: 'Ikibazo',
  our_objective: 'Intego yacu',
  problem_text: 'Gukoresha uburyo bwa gakondo bituma habaho ibihombo byinshi igihe habaye ihindagurika ry’amashanyarazi no kugenzura bidahagije ibidukikije.',
  objective_text: 'Intego ni ugushyiraho ikiraniro cyubwenge gihendutse kandi cyizewe, gitanga igenzura n’amakuru y’ako kanya kuri cloud.',
  technical_layers: 'Inzego z’Iyubakwa rya Tekiniki',
  project_contributors: 'Abagize Umushinga',
  ready_telemetry: 'Witeguye kubona amakuru y’ako kanya?',
  telemetry_cta_text: 'Injira muri dashboard urebe amakuru y’ako kanya ava ku byuma by’igenzura n’imikoreshereze y’imari.',
  perception_layer: 'Urwego rw’Isesengura',
  processing_layer: 'Urwego rw’Itunganya',
  application_layer: 'Urwego rwa Porogaramu',
  electronics_engineer: 'Injeniyeri wa Electronics',
  systems_engineer: 'Injeniyeri wa Sisitemu',
  fullstack_developer: 'Umuhanga Full-Stack',
  live_telemetry_dashboard: 'Imbonerahamwe y’Amakuru y’Ako Kanya',
  online: 'Bihujwe',
  offline: 'Byahagaritse',
  attention_needed: 'Birakenewe kwitabwaho',
  all_parameters_graph: 'Igishushanyo cy’Ibipimo Byose',
  request_submitted_success: 'Ubusabe bwoherejwe neza.',
  request_form_subtitle: 'Ohereza ubusabe bw’ibikorwa bya buri munsi kuri sisitemu.',
  request_type: 'Ubwoko bw’Ubusabe',
  title: 'Umutwe',
  details: 'Ibisobanuro',
  submit_request: 'Ohereza Ubusabe',
  short_request_title: 'Umutwe mugufi w’ubusabe',
  explain_request: 'Sobanura ubusabe bwawe neza',
  maintenance: 'Uburungabunge',
  sensor_calibration: 'Gutunganya Sensor',
  supply_request: 'Ubwoko bw’Ibikenerwa',
  home_hero_images: 'Amashusho ya Hero ku Ahabanza',
  manage_home_slider: 'Gucunga amashusho agaragara kuri slider yo ku ipaji y’ahabanza.',
  upload_new_image: 'Ohereza Ishusho Nshya',
  image_post_added: 'Ishusho yongeweho neza.',
  upload_image: 'Ohereza Ishusho',
  title_optional: 'Umutwe (Si ngombwa)',
  display_order: 'Uko Bikorwa',
  upload_desc: 'Ibisobanuro bizagaragara ku ipaji y’ahabanza',
  uploading: 'Birimo koherezwa...',
  publish_home: 'Ohereza ku Ahabanza',
  active_gallery: 'Galerie Ikora',
  images_count: 'Amashusho',
  preview: 'Reba',
  no_image_gallery: 'Nta shusho irimo muri galerie ubu.',
  order: 'Urutonde',
  edit_transaction_title: 'Hindura Igikorwa',
  add_transaction_title: 'Ongeraho Igikorwa',
  messages_room: 'Icyumba cy’Ubutumwa',
  unread: 'bitarasomwa',
  no_messages_yet: 'Nta butumwa buraza kugeza ubu.',
  mark_as_read: 'Shyira nk’ibyasomwe',
  history_log: 'Amateka',
  log_energy_bill: 'Bika fagitire y’ingufu',
  amount_rwf: 'Amafaranga (RWF)',
  enter_amount: 'Andika amafaranga',
  saving: 'Kubika...',
  date_col: 'Itariki',
  category_col: 'Icyiciro',
  type_col: 'Ubwoko',
  amount_col: 'Amafaranga',
  edit_transaction_btn: 'Hindura ibikorwa',
  delete_transaction_btn: 'Siba ibikorwa',
  delete_record_confirm: 'Urashaka gusiba iyi nyandiko?',
  ai_nexus_predictions: 'Ubuhanuzi bwa AI',
  predict_intro: 'Sisitemu yacu isesengura gahunda y’ikorwa ry’amagi igatanga ibisubizo n’inama z’igenzura ry’ubushyuhe n’umunyevu.',
  predict_results: 'Sohora Ibisubizo',
  hatch_success_probability: 'Icyizere cy\'ihitamo ry\'indwara',
  ai_predicted_hatch_date: 'Itariki y\'ihanura',
  technical_ai_recommendations: 'Inama za AI za Tekiniki',
  awaiting_data: 'Tegereje amakuru kugira ngo AI itange ibisubizo...',
  predictive_performance_analytics: 'Isesengura ry’Imikorere y’Ubuhanuzi',
  historical_accuracy: 'Ukuri kwa Kera',
  model_version: 'Verisiyo ya Modeli',
  processing_latency: 'Ubukererwe bw’Itunganya',
  deep_flash_learning: 'Kwiga byihuse byimbitse',
  realtime_edge_logic: 'Itunganya ry’ako kanya',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem('app_lang') as Language) || 'en'
  );

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string) => {
    if (language === 'rw') {
      return translations.rw[key] || kinyarwandaFallback[key] || translations.en[key] || englishFallback[key] || key;
    }
    return translations[language][key] || translations.en[key] || englishFallback[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within LanguageProvider');
  return context;
};
